sudo: false
addons:
  apt:
    sources: &common_sources
      - ubuntu-toolchain-r-test
    packages: &common_packages
      - oracle-java8-installer
      - libstdc++6
      - libstdc++6-4.7-dev
      - gcc-4.9
      - g++-4.9
      - swig
      - ccache

services:
  - docker

matrix:
  include:
    - os: linux
      jdk: oraclejdk9
      addons: &llvm40
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *common_packages
            - clang-4.0
            - libllvm4.0
            - llvm-4.0
            - llvm-4.0-dev
            - llvm-4.0-runtime
      env:
      - TESTED_LANGS="C Cpp IR"
      - CLANG_BIN=clang-4.0

    - os: linux
      jdk: openjdk9
      addons: 
        - *llvm40
      env:
      - TESTED_LANGS="C Cpp IR"
      - CLANG_BIN=clang-4.0
      
language: java

script: ./mvnw install dockerfile:build

after_success:
  - bash check.sh
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; ./mvnw dockerfile:push
  on:
    branch: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ccache
