sudo: false

services:
  - docker

language: minimal

script: docker build -t sanitytool/bitreader-service .

#after_success:
#  - bash check.sh
#  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push sanitytool/bitreader-service
#  on:
#    branch: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ccache
