sudo: false
addons:
  apt:
    sources: &common_sources
      - ubuntu-toolchain-r-test
    packages: &common_packages
      - oracle-java8-installer
      - libstdc++6
      - libstdc++6-4.7-dev
      - gcc-4.9
      - g++-4.9
      - swig
      - ccache

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons: &llvm40
        apt:
          sources:
            - *common_sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *common_packages
            - clang-4.0
            - libllvm4.0
            - llvm-4.0
            - llvm-4.0-dev
            - llvm-4.0-runtime
      env:
      - LANGS="C Cpp IR"
      - CLANG_BIN=clang-4.0

language: java

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ccache
